### ISSUE TITLE
How to pass some information from workflow context to all the activities.

### ISSUE THREAD

**Issue by Nagesh-Anna** [coinbase/temporal-ruby#266]
I am writing one workflow where I wanted to call 4 activities from this workflow.

I wanted to load the same user object in all these activities. Is there a way that we can pass this object to the activity context from the workflow context? If yes, Could you please help with some examples?

Also, does this get updated with time in the context or do we have to load every time to context?

I am happy to hear if there are any other alternatives.

Thanks in Advance!

**Comment by jeffschoner** [comment]
Workflows don't directly invoke activities in the same process. Rather a workflow schedules an activity task that will be picked up and executed by any worker polling that task queue. Because of this, you typically need to load the object in each activity based on inputs to the activity.

You can cache the data on local disk to reduce unnecessary reloading of an object. However, because activities can execute on any worker listening to a task queue, the cache miss rate will rapidly increase as your worker fleet size increases. To improve this, you can follow a pattern known as "activity stick queues". There's no sample for this in temporal-ruby, but the concept is illustrated in other Temporal SDKs: [.NET](https://github.com/temporalio/samples-dotnet/tree/main/src/ActivityStickyQueues), [Go](https://github.com/temporalio/samples-go/tree/main/activities-sticky-queues), [Python](https://github.com/temporalio/samples-python/tree/main/activity_sticky_queues), [Typescript](https://github.com/temporalio/samples-typescript/tree/main/worker-specific-task-queues).

This all will introduce increased complexity in your code. You have to decide if it's worth it or not. Another simple option is to consider combining multiple activities together so that the object only needs to be loaded once or a fewer number of times. There's downsides to this too: notably making the entire activity idempotent or setting tight timeouts may be more difficult, or you can lose parallelism.

**Comment by Nagesh-Anna** [comment]
Thank you
