### ISSUE TITLE
Cannot generate new async_token when same activity get called multiple times

### ISSUE THREAD

**Issue by tim37021** [coinbase/temporal-ruby#98]
Hi! I am doing some experiment on temporal-ruby. I find I cannot create new async_token. keep printing same token.
is there any problem during replaying of my workflow?

```ruby
module TemporalWorkflow
  class PollCommandActivity < Temporal::Activity
    retry_policy(
      interval: 1,
      backoff: 1,
      max_attempts: 30,
    )
    def execute
      puts "token #{activity.async_token}"
      activity.async
    end
  end
end
```

```ruby
module TemporalWorkflow
  class MyWorkflow < Temporal::Workflow
    def execute(message:)
      loop do
        cmd = PollCommandActivity.execute!
        break if cmd[:cmd] == "exit"
        klass = cmd[:cmd].safe_constantize
        cmd[:args] ||= []
        cmd[:kwargs] ||= {}
        klass.execute!(*cmd[:args], **cmd[:kwargs]) if klass
      end
    end
  end
end


```

**Comment by tim37021** [comment]
in my rails console
```ruby
Temporal.complete_activity(the_token, {cmd: "TemporalWorkflow::MyActivity", args: ["hi"]})
```
I am only able to do this twice.

**Comment by antstorm** [comment]
@tim37021 sorry for the slow response. I've just tried it locally and it works as expected. One thing that I've noticed is that even though async tokens are definitely different each time, they are also very similar. It's a base64 of a string that includes your namespace, activity_id, workflow_id and run_id. Because it's only the activity_id (which is an integer) that changes, the tokens end up looking very close. Here's an example from my test (notice 20th and 21st characters):

```
cnVieS1zYW1wbGVzfDE3fGUxZTMwNjU3LTdjY2YtNDkwYS1hZDFjLWJjZjhkNzA2NzE0OXwyZTU4MjNmYi00M2QyLTQ0ODktOTIxYi1kNTFjNTUzMGQ2MTU=
cnVieS1zYW1wbGVzfDI5fGUxZTMwNjU3LTdjY2YtNDkwYS1hZDFjLWJjZjhkNzA2NzE0OXwyZTU4MjNmYi00M2QyLTQ0ODktOTIxYi1kNTFjNTUzMGQ2MTU=
cnVieS1zYW1wbGVzfDQxfGUxZTMwNjU3LTdjY2YtNDkwYS1hZDFjLWJjZjhkNzA2NzE0OXwyZTU4MjNmYi00M2QyLTQ0ODktOTIxYi1kNTFjNTUzMGQ2MTU=
cnVieS1zYW1wbGVzfDUzfGUxZTMwNjU3LTdjY2YtNDkwYS1hZDFjLWJjZjhkNzA2NzE0OXwyZTU4MjNmYi00M2QyLTQ0ODktOTIxYi1kNTFjNTUzMGQ2MTU=
```

<img width="890" alt="Screenshot 2021-09-23 at 12 13 43" src="https://user-images.githubusercontent.com/118353/134498228-aa938875-a454-468a-ae77-fd793fbab073.png">

Trying to resubmit a previous token results in an error, as expected: `3:Cannot locate Activity ScheduleID`

Here's the code that I used (the only difference from yours should be the lack of `safe_constantize`):

```ruby
class AsyncActivityWorkflow < Temporal::Workflow
  def execute
    loop do
      cmd = AsyncActivity.execute!
      break if cmd[:cmd] == "exit"
      klass = Object.const_get(cmd[:cmd]) rescue nil
      cmd[:args] ||= []
      cmd[:kwargs] ||= {}
      klass.execute!(*cmd[:args], **cmd[:kwargs]) if klass
    end
  end
end
```

**Comment by tim37021** [comment]
Oh maybe I saw it and thought it was the same and quickly gave it up, let me setup my environment and try it again today. 
I remember for the first and second async is quite different.

**Comment by antstorm** [comment]
@tim37021 I saw the same behaviour, the first and the second tokens are more different from each other then the following ones, I think it's because activity_id for the first activity is a single digit, but the second one is 2 digits, which shifts all the bits in the base64 encoded token

**Comment by tim37021** [comment]
yeah, temporal-ruby use non-encryption approach to generate token. so changing one digit wont affect every character of the token.

**Comment by tim37021** [comment]
ok i can confirm it's my mistake
![image](https://user-images.githubusercontent.com/5507113/134811419-af683d7d-9592-4ad3-975b-796a1cc4e800.png)
